### PR TITLE
Fixes #6

### LINKED ISSUE #6: Error in path generation in {ts, js}config.json
If you execute this command:

```
$ mrdeveloper --config=jsconfig.json --output=addons
```

Then the output is:

```
{
    "compilerOptions": {
        "paths": {
            "@plone/my-volto-addon": [
                "develop/@plone/my-volto-addon"
            ]
        },
        "baseUrl": "src"
    }
}
```

instead of being:

```
            "@plone/my-volto-addon": [
                "addons/@plone/my-volto-addon"
            ]
```

### PR DESCRIPTION
**Pull request by sneridagh**

### CODE REVIEW

**Comment by sneridagh** [comment]
Sorry for the trailing spaces changes in the diff... BTW I already had to disable Prettier on saving it :P Ah, these TS fanatics... ;)

**Comment by sneridagh** [comment]
Also sorry but hadn't time to write a test for it... Can I haz a release too? Thx!!

**Comment by sneridagh** [comment]
@ebrehault ping! :) Please can you take a look at it? Thanks!

**Review by ebrehault — APPROVED** [review]

**Comment by ebrehault** [comment]
Merged and published!

Sorry for the delay I was in vacations :)

**Comment by sneridagh** [comment]
Thanks a lot Eric!!!

**Pull request merged**
